In [ ]:
import numpy as np

arr_1d = np.array([1,2,3])
print(arr_1d)

#2d array
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.ndim)

#3d array
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)
print(arr_3d.ndim)

 #dimwnsion
a=np.array([1,2,3,4])
print(a.ndim)

#dimension
b=np.array(24)
print(b.ndim)

#array of zeros
array_zeros = np.zeros((2,3))
print(array_zeros)

#array of ones
array_ones = np.ones((2,3))
print(array_ones)

#array of random numbers
array_random = np.random.random((4,3))
print(array_random)

#identity matrix
identity = np.eye(4)
print(identity)

#array with range of values
arr_range = np.arange(1,11,3) #start,stop,step
print(arr_range)

#array attributes
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("shape: ",arr.shape)
print("size: ",arr.size)
print("datatype: ",arr.dtype)
print("no of dimensions: ",arr.ndim)

[1 2 3]
[[1 2 3]
 [4 5 6]]
2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
1
0
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.76220182 0.72371449 0.3232014 ]
 [0.6137934  0.92974865 0.50836767]
 [0.67125319 0.64391795 0.13723544]
 [0.32828929 0.58671029 0.92168068]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 1  4  7 10]
shape:  (2, 2, 3)
size:  12
datatype:  int64
no of dimensions:  3


In [ ]:
import numpy as np
temp_data = np.array([[22,25,20],[24,26,23]])
print(temp_data)

#array properties
print("shape: ",temp_data.shape)
print("size: ",temp_data.size)
print("datatype: ",temp_data.dtype)
print("no of dimensions: ",temp_data.ndim)

#adding third gh
a1 = np.array([[21,23,22]])
updated_temp_data = np.append(temp_data,a1,axis=0)

#zeros array
sensor_error_flags = np.zeros((2,3))

#identity array
greenhouse_identity = np.ones((3,3))

print("updated temp data: ",updated_temp_data)
print("sensor_error_flags: ",sensor_error_flags)
print("greenhouse_identity: ",greenhouse_identity)

[[22 25 20]
 [24 26 23]]
shape:  (2, 3)
size:  6
datatype:  int64
no of dimensions:  2
updated temp data:  [[22 25 20]
 [24 26 23]
 [21 23 22]]
sensor_error_flags:  [[0. 0. 0.]
 [0. 0. 0.]]
greenhouse_identity:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

#indexing and slicing
arr = np.array([[1,2,3],[4,5,6]]) #index starts from zero
print(arr[1,2]) #index:-1 is last element of that row
print(arr[1,-2])

#slicing
print(arr[:,1:]) #[start:end] or [start:end:step]

6
5
[[2 3]
 [5 6]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
import numpy as np
#Create the 2D NumPy array
shipments = np.array([[50,60,55,70,65,80,90],[40,45,30,60,55,70,75]])
print(shipments)

#Apples shipped on Wednesday
print("Apples shipped on Wednesday: ",shipments[0,2])

#Oranges shipped on Sunday
print("Oranges shipped on Sunday: ",shipments[1,-1])

#weekday shipments (Mon–Fri)
print("weekday shipments (Mon–Fri): ",shipments[:,0:5])

#weekend shipments (Sat & Sun)
print("weekend shipments (Sat & Sun): ",shipments[:,-2:])

#Apples from Wednesday to Saturday
print("Apples from Wednesday to Saturday: ",shipments[0,2:])

#Replace the Saturday shipment of Apples (currently 80) with 100 using indexing
shipments[0,-2] = 100
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 30 60 55 70 75]]
Apples shipped on Wednesday:  55
Oranges shipped on Sunday:  75
weekday shipments (Mon–Fri):  [[50 60 55 70 65]
 [40 45 30 60 55]]
weekend shipments (Sat & Sun):  [[80 90]
 [70 75]]
Apples from Wednesday to Saturday:  [55 70 65 80 90]
[[ 50  60  55  70  65 100  90]
 [ 40  45  30  60  55  70  75]]


In [ ]:
#array operations

#arithmetic
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(a*2)

#matrix operations

#matrix multiplication
mat1 = np.array([1,2,3])
mat2 = np.array([4,5,6])
mul = np.dot(mat1,mat2)
print(mul)

[5 7 9]
[ 4 10 18]
[2 4 6]
32


In [ ]:
#Broadcasting
#numpy automatically applies operations across arrays of different shapes when compatible

a = np.array([1,2,3])
b = 2
print(a+b)

a = np.array([[1,2,3],[3,4,5]])
b = 2
print(a+b)

[3 4 5]
[[3 4 5]
 [5 6 7]]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

```
# This is formatted as code

1.   List item
2.   List item


```



In [ ]:
#universal functions

#exponentiation
arr = np.array([1,2,3])
print(np.exp(arr))

#square root
print(np.sqrt(arr))

#logarithm
print(np.log(arr))

print(np.trunc(3.567))

print(np.logical_and(True,False))

print(np.greater(30,57))

print(np.bitwise_and(89,45)) #converts both values into binary and performs add opertions for corresponding binary values

print(np.invert(89)) #add 1 to the value

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
3.0
False
False
9
-90


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [11]:
import numpy as np
#Create arrays
farmA = np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB = np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC = np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])

#Stack them into a single 3D array production_all
production_all = np.array([farmA,farmB,farmC])
print(production_all)

#Array attributes
print("shape: ",production_all.shape)
print("size: ",production_all.size)
print("datatype: ",production_all.dtype)
print("no of dimensions: ",production_all.ndim)

#Per-farm totals (arithmetic & aggregation)

sa = np.sum(farmA[:,:])
sb = np.sum(farmB[:,:])
sc = np.sum(farmC[:,:])
perfarm_totals = np.array([sa,sb,sc])
print("perfarm_totals: ",perfarm_totals)
print("mean: ",np.mean(perfarm_totals))
print("standard deviation: ",np.std(perfarm_totals))
print("variance: ",np.var(perfarm_totals))


#Per-hour matrix multiplication idea (matrix op)
hour_weights = np.array([0.5,1.0,0.75])
print("hour_weights: ",hour_weights)

#weighted_per_panel
#per_panel_weighted_energy = np.dot()

#5. Broadcasting adjustments
farmB = farmB + 0.5
production_all = np.array([farmA,farmB,farmC])
print(production_all)

perfarm_mean = np.mean(production_all)
perfarm_std = np.std(production_all)

print("\nPer-farm mean:\n", perfarm_mean)
print("Per-farm std:\n", perfarm_std)

# Z-score normalization
normalized = (production_all - perfarm_mean) / perfarm_std
print("\nNormalized (z-score) production_all:\n", normalized)

print("shape: ",normalized.shape)
print("size: ",normalized.size)
print("datatype: ",normalized.dtype)

# exponential family functions
exp_data = np.exp(normalized)
expm1_data = np.expm1(normalized)
log_data = np.log(np.clip(normalized, a_min=1e-6, a_max=None))
log10_data = np.log10(np.clip(normalized, a_min=1e-6, a_max=None))
log2_data = np.log2(np.clip(normalized, a_min=1e-6, a_max=None))
print(exp_data)

# Trigonometric ufuncs
sin_data = np.sin(normalized)
cos_data = np.cos(normalized)
tan_data = np.tan(normalized)
arcsin_data = np.arcsin(np.clip(normalized/np.max(np.abs(normalized)), -1, 1))
arccos_data = np.arccos(np.clip(normalized/np.max(np.abs(normalized)), -1, 1))
arctan_data = np.arctan(normalized)

# Convert radians <-> degrees
to_degrees = np.degrees(arctan_data)
to_radians = np.radians(to_degrees)

print("\nTrigonometric summary:")
print("sin mean:", np.mean(sin_data), "cos mean:", np.mean(cos_data))
print("arctan first row of farmB:\n", arctan_data[1,0])

# Rounding ufuncs
round_data = np.round(normalized)
floor_data = np.floor(normalized)
ceil_data = np.ceil(normalized)
trunc_data = np.trunc(normalized)

print("\nRounding summary:")
print("Rounded (farmA first row):", round_data[0,0])
print("Floor (farmA first row):", floor_data[0,0])

#Comparison & Logical ufuncs
high_output = production_all > 20
even_hours_mask = (production_all % 2 == 0)

and_mask = np.logical_and(high_output, even_hours_mask)
or_mask = np.logical_or(high_output, even_hours_mask)
not_mask = np.logical_not(high_output)
xor_mask = np.logical_xor(high_output, even_hours_mask)

greater_equal_mask = np.greater_equal(production_all, 15)
less_mask = np.less(production_all, 10)

print("\nComparison summary:")
print("high_output count:", np.sum(high_output))
print("AND mask count:", np.sum(and_mask))

#Bitwise ufuncs (integer arrays)
alerts = np.array([[1,0,1],
                   [0,0,1],
                   [1,1,0],
                   [0,1,0]])
alerts_all = np.array([alerts, alerts, alerts])  # match (3,4,3)
bit_and = np.bitwise_and(alerts_all, (production_all > 15).astype(int))
bit_or = np.bitwise_or(alerts_all, (production_all > 15).astype(int))
bit_not = np.invert(alerts_all.astype(bool))

print("\nBitwise summary:")
print("bit_and first farm first row:", bit_and[0,0])
print("bit_not first farm first row:", bit_not[0,0])

#Arithmetic ufuncs
add_data = np.add(normalized, 2)
sub_data = np.subtract(normalized, 1)
mul_data = np.multiply(normalized, 3)
div_data = np.divide(normalized, 2)
pow_data = np.power(normalized, 2)
mod_data = np.mod(normalized, 2)

print("\nArithmetic summary:")
print("Add first row of farmA:", add_data[0,0])

# Aggregations
print("Sum of exp(normalized):", np.sum(exp_data))
print("Mean of sin(normalized):", np.mean(sin_data))

#broadcast-based summary table
panel_totals_per_farm = np.sum(production_all, axis=2)  # sum across hours
needs_maintenance = np.any(panel_totals_per_farm < 40)

print("\nBroadcast summary:")
print("panel_totals_per_farm:\n", panel_totals_per_farm)
print("needs_maintenance:", needs_maintenance)

#Final KPIs (aggregations)
overall_total = np.sum(production_all)
peak_value = np.max(production_all)
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
avg_per_panel = np.mean(production_all, axis=(1,2))

print("\nFinal KPIs:")
print("Overall total:", overall_total)
print("Peak value:", peak_value)
print("Peak location (farm, panel, hour):", peak_index)
print("Average per panel (each farm):", avg_per_panel)

[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
shape:  (3, 4, 3)
size:  36
datatype:  int64
no of dimensions:  3
perfarm_totals:  [126 234 174]
mean:  178.0
standard deviation:  44.181444068749045
variance:  1952.0
hour_weights:  [0.5  1.   0.75]
[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]

Per-farm mean:
 15.0
Per-farm std:
 4.368447474027052

Normalized (z-score) production_all:
 [[[-1.14457139 -0.68674283 -0.91565711]
  [-1.37348567 -0.91565711 -1.14457139]
  [-0.68674283 -0.45782856 -0.22891428]
  [-1.60239995 -1.83131422 -1.37348567]]

 [[ 1.25902853  1.03011425  1.48794281]
  [ 0.80119997  1.25902853  1.03011425]
  [ 1.71685709  1.94577136  1.48794281]
  [ 0.5722857   0.80119997  

In [ ]:
#Reshaping arrays
arr = np.array([1,2,3,4,5])
reshaped = arr.reshape(1,3)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4]
[3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]
